"""TPAA Evaluation Context contracts."""

from .m8_p4_p5 import (
    M8AdmissionEvidence,
    M8AuthorityPolicy,
    M8GovernanceError,
    M8RoleModelBinding,
    M8RoleRule,
    P3ClaimEnvelope,
    assert_annotation_body_allowed,
    assert_capability_claim_allowed,
    assert_p3_claim_preserved,
    assert_scope_copy_allowed,
    assert_write_allowed,
    canonical_hash,
    exact_hash64,
    exact_text,
    exact_uuid,
    project_direct_actor_id,
    pseudonymous_subject_key,
    utc,
    validate_availability_numeric,
    validate_role_model_binding,
)
from .resolver import (
    ContextArtifactRef,
    EvaluationContextError,
    ResolvedEvaluationContext,
    resolve_all_evaluation_contexts,
    resolve_evaluation_context,
)

__all__ = [
    "ContextArtifactRef",
    "EvaluationContextError",
    "M8AdmissionEvidence",
    "M8AuthorityPolicy",
    "M8GovernanceError",
    "M8RoleModelBinding",
    "M8RoleRule",
    "P3ClaimEnvelope",
    "ResolvedEvaluationContext",
    "assert_annotation_body_allowed",
    "assert_capability_claim_allowed",
    "assert_p3_claim_preserved",
    "assert_scope_copy_allowed",
    "assert_write_allowed",
    "canonical_hash",
    "exact_hash64",
    "exact_text",
    "exact_uuid",
    "project_direct_actor_id",
    "pseudonymous_subject_key",
    "resolve_all_evaluation_contexts",
    "resolve_evaluation_context",
    "utc",
    "validate_availability_numeric",
    "validate_role_model_binding",
]
