from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEV_CLI = REPO_ROOT / "tools" / "dev" / "tpaa_dev.py"
GENERATED = REPO_ROOT / "src" / "tpaa_generated"


def _run(*args: str, cwd: Path = REPO_ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(args),
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
    )


def test_all_generated_python_files_have_source_and_generator_provenance() -> None:
    manifest = json.loads((GENERATED / "_generation_manifest.json").read_text(encoding="utf-8"))
    by_output: dict[str, tuple[str, list[dict[str, str]]]] = {}
    for generator in manifest["generators"]:
        for output in generator["outputs"]:
            by_output[output["path"]] = (generator["generator_id"], generator["sources"])

    python_paths = sorted(path for path in GENERATED.glob("*.py"))
    assert python_paths
    for path in python_paths:
        relative = path.relative_to(REPO_ROOT).as_posix()
        generator_id, sources = by_output[relative]
        text = path.read_text(encoding="utf-8")
        assert text.startswith("# @generated by TPAA codegen; DO NOT EDIT BY HAND.\n")
        assert f"# generator_id={generator_id}\n" in text
        assert f"# generator_version={manifest['generator_version']}\n" in text
        assert sources
        for source in sources:
            expected = (
                f"# source artifact_id={source['artifact_id']} "
                f"version={source['version']} sha256={source['sha256']}\n"
            )
            assert expected in text


def test_verify_generated_passes_on_checked_in_tree() -> None:
    result = _run(sys.executable, str(DEV_CLI), "verify-generated")
    assert result.returncode == 0, result.stderr
    assert '"status": "PASS"' in result.stdout


def test_verify_generated_rejects_one_byte_drift_and_restore_passes() -> None:
    target = GENERATED / "baseline.py"
    original = target.read_bytes()
    try:
        target.write_bytes(original + b"# manual drift\n")
        failed = _run(sys.executable, str(DEV_CLI), "verify-generated")
        assert failed.returncode == 2
        assert "GENERATED_FILE_DRIFT" in failed.stdout
    finally:
        target.write_bytes(original)
    assert _run(sys.executable, str(DEV_CLI), "verify-generated").returncode == 0


def test_verify_generated_rejects_unexpected_file() -> None:
    rogue = GENERATED / "manual_override.py"
    try:
        rogue.write_text("VALUE = 'manual'\n", encoding="utf-8", newline="\n")
        failed = _run(sys.executable, str(DEV_CLI), "verify-generated")
        assert failed.returncode == 2
        assert "UNEXPECTED_GENERATED_FILE" in failed.stdout
    finally:
        rogue.unlink(missing_ok=True)


def test_verify_generated_rejects_missing_file() -> None:
    target = GENERATED / "stage_registry.py"
    backup = target.read_bytes()
    target.unlink()
    try:
        failed = _run(sys.executable, str(DEV_CLI), "verify-generated")
        assert failed.returncode == 2
        assert "GENERATED_FILE_MISSING" in failed.stdout
    finally:
        target.write_bytes(backup)


def test_regenerate_diff_refuses_uncommitted_generated_change_without_overwrite() -> None:
    target = GENERATED / "baseline.py"
    original = target.read_bytes()
    drifted = original + b"# uncommitted manual edit\n"
    try:
        target.write_bytes(drifted)
        failed = _run(sys.executable, str(DEV_CLI), "regenerate-diff")
        assert failed.returncode == 2
        assert "GENERATED_TREE_DIRTY" in failed.stderr
        assert target.read_bytes() == drifted
    finally:
        target.write_bytes(original)


def test_regenerate_diff_blocks_committed_manual_edit_in_clean_git_checkout(tmp_path: Path) -> None:
    clone = tmp_path / "repo"
    shutil.copytree(
        REPO_ROOT,
        clone,
        ignore=shutil.ignore_patterns(".git", ".venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"),
    )
    assert _run("git", "init", "-b", "main", cwd=clone).returncode == 0
    assert _run("git", "config", "user.name", "TPAA Test", cwd=clone).returncode == 0
    assert _run("git", "config", "user.email", "tpaa-test@example.invalid", cwd=clone).returncode == 0
    assert _run("git", "add", ".", cwd=clone).returncode == 0
    assert _run("git", "commit", "-m", "fixture baseline", cwd=clone).returncode == 0

    clean_gate = _run(sys.executable, "tools/dev/tpaa_dev.py", "regenerate-diff", cwd=clone)
    assert clean_gate.returncode == 0, clean_gate.stderr

    target = clone / "src" / "tpaa_generated" / "baseline.py"
    target.write_bytes(target.read_bytes() + b"# committed manual edit\n")
    assert _run("git", "add", str(target.relative_to(clone)), cwd=clone).returncode == 0
    assert _run("git", "commit", "-m", "manual generated edit", cwd=clone).returncode == 0

    failed = _run(sys.executable, "tools/dev/tpaa_dev.py", "regenerate-diff", cwd=clone)
    assert failed.returncode == 2
    assert "REGENERATE_DIFF_FAILED" in failed.stderr
