"""M4 P1 longitudinal domain."""

from .m4_release import (
    InMemoryM4LongitudinalReleaseRepository,
    M4LongitudinalPublicationService,
    M4LongitudinalReleaseInput,
    M4LongitudinalReleaseSnapshot,
    M4PublishedLongitudinalRelease,
    M4PublishResult,
    M4ReplayComparison,
    M4ReplayView,
    allocate_m4_longitudinal_release_id,
    build_m4_longitudinal_release,
    compare_m4_longitudinal_replay,
)
from .m4_sample import (
    M4LongitudinalAuthority,
    M4LongitudinalEligibility,
    M4LongitudinalError,
    M4LongitudinalSample,
    M4LongitudinalScope,
    M4SourceObservation,
    build_comparison_key,
    build_longitudinal_sample,
    build_longitudinal_scope,
    build_m4_longitudinal_eligibility,
    load_m4_longitudinal_authority,
    validate_m4_product_scope,
)
from .m4_trend import (
    M4PerformanceTrendPoint,
    M4PerformanceTrendSeries,
    M4TrendAuthority,
    M4TrendBridge,
    build_performance_trend_series,
    load_m4_trend_authority,
)
from .p3_substrate import (
    P3AdjustedEstimateInput,
    P3AdmissionEvidence,
    P3AuthorityPolicy,
    P3GovernanceError,
    P3LifecycleEventInput,
    P3LifecycleSegment,
    P3ManagedObject,
    P3ModelValidationSnapshot,
    assert_capability_claim_allowed,
    assert_p1_p2_immutable,
    assert_p3_claim_level,
    build_p3_lifecycle_segment,
    build_p3_validation_snapshot,
    project_p2_adjusted_estimate,
    validate_managed_object,
)

__all__ = [
    "InMemoryM4LongitudinalReleaseRepository",
    "M4LongitudinalAuthority",
    "M4LongitudinalEligibility",
    "M4LongitudinalError",
    "M4LongitudinalPublicationService",
    "M4LongitudinalReleaseInput",
    "M4LongitudinalReleaseSnapshot",
    "M4LongitudinalSample",
    "M4LongitudinalScope",
    "M4PerformanceTrendPoint",
    "M4PerformanceTrendSeries",
    "M4PublishedLongitudinalRelease",
    "M4PublishResult",
    "M4ReplayComparison",
    "M4ReplayView",
    "M4SourceObservation",
    "M4TrendAuthority",
    "M4TrendBridge",
    "P3AdjustedEstimateInput",
    "P3AdmissionEvidence",
    "P3AuthorityPolicy",
    "P3GovernanceError",
    "P3LifecycleEventInput",
    "P3LifecycleSegment",
    "P3ManagedObject",
    "P3ModelValidationSnapshot",
    "assert_capability_claim_allowed",
    "assert_p1_p2_immutable",
    "assert_p3_claim_level",
    "build_p3_lifecycle_segment",
    "build_p3_validation_snapshot",
    "project_p2_adjusted_estimate",
    "validate_managed_object",
    "allocate_m4_longitudinal_release_id",
    "build_comparison_key",
    "build_longitudinal_sample",
    "build_longitudinal_scope",
    "build_m4_longitudinal_eligibility",
    "build_m4_longitudinal_release",
    "build_performance_trend_series",
    "compare_m4_longitudinal_replay",
    "load_m4_longitudinal_authority",
    "load_m4_trend_authority",
    "validate_m4_product_scope",
]

from .p4_replay import (
    P4AssessmentProjection,
    P4LongitudinalReplay,
    P4ReplayRevision,
    build_p4_longitudinal_replay,
)

__all__ += [
    "P4AssessmentProjection",
    "P4LongitudinalReplay",
    "P4ReplayRevision",
    "build_p4_longitudinal_replay",
]
