"""M1/M2 Observation and Release publication domain."""

from .m2_publication import (
    M2_PUBLICATION_ROUTE_CONTRACTS,
    M2MetricPublicationTarget,
    M2PublicationRouteContract,
    M2PublicationRoutingError,
    M2PublicationRoutingPlan,
    build_m2_publication_routing_plan,
    route_m2_metric_definition,
)
from .m2_release import (
    M2ImmutableReleaseSnapshot,
    M2ReleaseBindingSnapshot,
    M2ReleaseDefinitionSnapshot,
    M2ReleaseExecutionSnapshot,
    M2ReleaseSnapshotError,
    allocate_m2_release_id,
    build_m2_release_snapshot,
)
from .m3_publication import (
    M3_PUBLICATION_LANE_COUNTS,
    M3_PUBLICATION_METRIC_COUNT,
    M3_PUBLICATION_ROUTE_COUNTS,
    M3PublicationRoutingPlan,
    build_m3_publication_routing_plan,
)
from .publication import (
    AircraftPublicationIdentity,
    CapabilityObservationRecord,
    EvidenceRefSnapshot,
    ImmutableEvidenceSet,
    ImmutableMetricDefinition,
    ImmutableMetricInstance,
    PublicationError,
    ReplayComparison,
    SessionRelease,
    allocate_session_release_id,
    build_session_release,
    compare_replay,
)

__all__ = [
    "AircraftPublicationIdentity",
    "M2MetricPublicationTarget",
    "M2PublicationRouteContract",
    "M2PublicationRoutingError",
    "M2PublicationRoutingPlan",
    "M2_PUBLICATION_ROUTE_CONTRACTS",
    "M2ImmutableReleaseSnapshot",
    "M2ReleaseBindingSnapshot",
    "M2ReleaseDefinitionSnapshot",
    "M2ReleaseExecutionSnapshot",
    "M2ReleaseSnapshotError",
    "M3_PUBLICATION_LANE_COUNTS",
    "M3_PUBLICATION_METRIC_COUNT",
    "M3_PUBLICATION_ROUTE_COUNTS",
    "M3PublicationRoutingPlan",
    "allocate_m2_release_id",
    "build_m2_publication_routing_plan",
    "build_m2_release_snapshot",
    "build_m3_publication_routing_plan",
    "route_m2_metric_definition",
    "CapabilityObservationRecord",
    "EvidenceRefSnapshot",
    "ImmutableEvidenceSet",
    "ImmutableMetricDefinition",
    "ImmutableMetricInstance",
    "PublicationError",
    "ReplayComparison",
    "SessionRelease",
    "allocate_session_release_id",
    "build_session_release",
    "compare_replay",
]
