#!/usr/bin/env python3
"""Run TPAA deterministic code generation through the approved loader boundary."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tpaa_canonical import CanonicalArtifactLoader  # noqa: E402
from tpaa_codegen import GenerationCoordinator, default_generators  # noqa: E402
from tpaa_codegen.governance import verify_generated_tree  # noqa: E402



def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic TPAA source projections")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Build in memory and fail if checked-in generated bytes differ",
    )
    args = parser.parse_args()

    loader = CanonicalArtifactLoader()
    coordinator = GenerationCoordinator(loader, default_generators())
    summary = coordinator.build()

    if args.check:
        try:
            report = verify_generated_tree(REPO_ROOT, summary.files)
        except Exception as exc:
            print(f"CODEGEN_CHECK_FAIL {exc}", file=sys.stderr)
            return 2
        print(
            f"CODEGEN_CHECK_PASS files={len(report.expected_files)} "
            "governance=exact-tree+provenance"
        )
        return 0

    coordinator.write(REPO_ROOT)
    for generated in summary.files:
        print(
            "CODEGEN_WRITE "
            f"path={generated.relative_path.as_posix()} "
            f"sha256={generated.sha256} bytes={len(generated.content)}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
