#!/usr/bin/env python3
"""Run TPAA deterministic code generation through the approved loader boundary."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tpaa_canonical import CanonicalArtifactLoader  # noqa: E402
from tpaa_codegen import GenerationCoordinator  # noqa: E402
from tpaa_codegen.generators import (  # noqa: E402
    BaselineMetadataGenerator,
    DtoTypesGenerator,
    MetricRegistryGenerator,
    ProgramRegistryGenerator,
    StageRegistryGenerator,
)


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic TPAA source projections")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Build in memory and fail if checked-in generated bytes differ",
    )
    args = parser.parse_args()

    loader = CanonicalArtifactLoader()
    coordinator = GenerationCoordinator(
        loader, [
            BaselineMetadataGenerator(),
            ProgramRegistryGenerator(),
            StageRegistryGenerator(),
            MetricRegistryGenerator(),
            DtoTypesGenerator(),
        ]
    )
    summary = coordinator.build()

    if args.check:
        mismatches: list[str] = []
        for generated in summary.files:
            target = REPO_ROOT.joinpath(*generated.relative_path.parts)
            if not target.is_file():
                mismatches.append(f"missing:{generated.relative_path.as_posix()}")
                continue
            if target.read_bytes() != generated.content:
                mismatches.append(
                    f"changed:{generated.relative_path.as_posix()}:"
                    f"expected_sha256={generated.sha256}:actual_sha256={_digest(target)}"
                )
        if mismatches:
            print("CODEGEN_CHECK_FAIL " + " ".join(mismatches), file=sys.stderr)
            return 2
        print(f"CODEGEN_CHECK_PASS files={len(summary.files)} generator_version=0.1.0")
        return 0

    coordinator.write(REPO_ROOT)
    for generated in summary.files:
        print(
            "CODEGEN_WRITE "
            f"path={generated.relative_path.as_posix()} "
            f"sha256={generated.sha256} bytes={len(generated.content)}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
