#!/usr/bin/env python3
"""Machine-readable acceptance verifier for M0-CORE-003."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from tpaa_canonical import CanonicalArtifactLoader  # noqa: E402
from tpaa_codegen import GenerationCoordinator, default_generators  # noqa: E402

GENERATORS = list(default_generators())

def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _head() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip() if result.returncode == 0 else "UNAVAILABLE"


def _import_generated(name: str) -> bool:
    path = SRC_ROOT / "tpaa_generated" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_tpaa_codegen_verify_{name}", path)
    if spec is None or spec.loader is None:
        return False
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return True


def verify() -> dict[str, object]:
    loader = CanonicalArtifactLoader()
    coordinator = GenerationCoordinator(loader, GENERATORS)
    first = coordinator.build()
    second = coordinator.build()
    first_map = {f.relative_path.as_posix(): f.content for f in first.files}
    second_map = {f.relative_path.as_posix(): f.content for f in second.files}

    checks: list[dict[str, object]] = []

    def add(check_id: str, passed: bool, detail: str) -> None:
        checks.append({"check_id": check_id, "status": "PASS" if passed else "FAIL", "detail": detail})

    add("DETERMINISTIC-REBUILD", first_map == second_map, f"files={len(first_map)}")

    checked_in_ok = True
    mismatches: list[str] = []
    for relative, expected in sorted(first_map.items()):
        path = REPO_ROOT.joinpath(*Path(relative).parts)
        if not path.is_file() or path.read_bytes() != expected:
            checked_in_ok = False
            mismatches.append(relative)
    add("CHECKED-IN-BYTES", checked_in_ok, "mismatches=" + ",".join(mismatches) if mismatches else "all generated bytes exact")

    imports_ok = all(_import_generated(name) for name in ("baseline", "program_registry", "stage_registry", "metric_registry", "dto"))
    add("GENERATED-IMPORTS", imports_ok, "5 generated domain Python modules import")

    manifest = json.loads(first.manifest_file.content)
    generator_ids = {entry["generator_id"] for entry in manifest["generators"]}
    expected_generators = {generator.generator_id for generator in GENERATORS}
    add("GENERATOR-COVERAGE", generator_ids == expected_generators, f"generators={sorted(generator_ids)}")

    source_ids = {
        source["artifact_id"]
        for entry in manifest["generators"]
        for source in entry["sources"]
    }
    expected_sources = {
        "BASELINE_LOCK",
        "CAPABILITY_PHASE_REGISTRY",
        "DEVELOPMENT_MILESTONE_REGISTRY",
        "ENGINEERING_WORKSTREAM_REGISTRY",
        "STAGE_REGISTRY",
        "P1_METRIC_CATALOG",
        "CROSS_LAYER_DTO_CONTRACTS",
    }
    add("CANONICAL-SOURCE-COVERAGE", source_ids == expected_sources, f"sources={sorted(source_ids)}")

    manifest_hashes_ok = all(
        output["sha256"] == _sha256(first_map[output["path"]])
        for entry in manifest["generators"]
        for output in entry["outputs"]
    )
    add("MANIFEST-OUTPUT-HASHES", manifest_hashes_ok, "manifest output hashes match generated bytes")

    forbidden_found: list[str] = []
    for path in sorted((SRC_ROOT / "tpaa_codegen" / "generators").glob("*.py")):
        text = path.read_text(encoding="utf-8")
        if "baseline/CB-" in text or "json.load(" in text or "json.loads(" in text:
            forbidden_found.append(path.name)
    add("LOADER-BOUNDARY", not forbidden_found, "direct Canonical parsing files=" + ",".join(forbidden_found) if forbidden_found else "no generator bypass detected")

    status = "PASS" if all(check["status"] == "PASS" for check in checks) else "FAIL"
    return {
        "evidence_schema": "TPAA_M0_GATE_EVIDENCE_V1",
        "task_id": "M0-CORE-003",
        "gate_id": "M0-CORE-003.CODE_GENERATOR_FRAMEWORK",
        "workstream": "WS-CORE",
        "status": status,
        "source_revision": _head(),
        "core_baseline": loader.expected_core_baseline,
        "baseline_lock_sha256": loader.trusted_lock_sha256,
        "generator_version": manifest["generator_version"],
        "generated_file_count": len(first_map),
        "generator_count": len(expected_generators),
        "checks": checks,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", type=Path)
    args = parser.parse_args()
    evidence = verify()
    text = json.dumps(evidence, indent=2, sort_keys=True) + "\n"
    if args.evidence is not None:
        args.evidence.parent.mkdir(parents=True, exist_ok=True)
        args.evidence.write_text(text, encoding="utf-8", newline="\n")
    print(text, end="")
    return 0 if evidence["status"] == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
