from __future__ import annotations

from .models import SourceArtifactRef

GENERATED_MARKER = "# @generated by TPAA codegen; DO NOT EDIT BY HAND."


def provenance_header(
    *,
    generator_id: str,
    generator_version: str,
    sources: tuple[SourceArtifactRef, ...],
) -> bytes:
    lines = [
        GENERATED_MARKER,
        f"# generator_id={generator_id}",
        f"# generator_version={generator_version}",
    ]
    for source in sorted(sources, key=lambda item: item.artifact_id):
        lines.append(
            "# source "
            f"artifact_id={source.artifact_id} "
            f"version={source.version} "
            f"sha256={source.sha256}"
        )
    return ("\n".join(lines) + "\n").encode("utf-8")


def decorate_python_source(
    content: bytes,
    *,
    generator_id: str,
    generator_version: str,
    sources: tuple[SourceArtifactRef, ...],
) -> bytes:
    return provenance_header(
        generator_id=generator_id,
        generator_version=generator_version,
        sources=sources,
    ) + content
