"""Governed TPAA World product contracts."""

from .m2_radar_sensor import (
    M2RadarSensorWorld,
    M2RadarSensorWorldError,
    build_m2_radar_sensor_world,
    project_m2_radar_sensor_world,
)
from .m2_reference_time import (
    CORE_WORLD_MANIFEST_FIELDS,
    CORE_WORLD_MANIFEST_WRITABLE_FIELDS,
    CoreWorldManifest,
    M2ReferenceTimeWorld,
    M2ReferenceTimeWorldError,
    build_m2_reference_time_world,
    project_m2_reference_time_world,
)
from .m2_stage_lineage import (
    M2StageWorldLineage,
    M2StageWorldLineageError,
    M2StageWorldLineageRecord,
    M2StageWorldLineageSummary,
    build_m2_stage_world_lineage,
    project_m2_stage_world_lineage,
)
from .m3_mission_product_applicability import (
    M3FamilyApplicabilityContract,
    M3MissionProductApplicability,
    M3MissionProductApplicabilityError,
    M3MissionProductInputSet,
    M3MissionSystemSubject,
    load_m3_mission_product_inputs,
    project_m3_family_applicability,
)
from .m3_profile_training import (
    M3ProfileEpisode,
    M3ProfileProjection,
    M3ProfileStage,
    M3ProfileStageEvent,
    M3ProfileWorldError,
    project_m3_training_profile,
)
from .m3_wvr_training import (
    M3WVREpisode,
    M3WVRProjection,
    M3WVRStage,
    M3WVRStageEvent,
    M3WVRWorldError,
    project_m3_wvr_world,
)
from .minimal_p1 import (
    AircraftObservedWorld,
    WorldEvidenceRef,
    WorldProjectionError,
    project_minimal_p1_world,
)
from .p4_p5_scope import (
    M8EvidenceRef,
    M8WorldFactRef,
    P4InteractionScopeSnapshot,
    P5CompositionSnapshot,
    P5ParticipantBinding,
    assert_composition_identity,
    assert_world_facts_immutable,
    build_p4_interaction_scope_snapshot,
    build_p5_composition_snapshot,
)

__all__ = [
    "AircraftObservedWorld",
    "CORE_WORLD_MANIFEST_FIELDS",
    "CORE_WORLD_MANIFEST_WRITABLE_FIELDS",
    "CoreWorldManifest",
    "M2RadarSensorWorld",
    "M2RadarSensorWorldError",
    "M2ReferenceTimeWorld",
    "M2ReferenceTimeWorldError",
    "M2StageWorldLineage",
    "M2StageWorldLineageError",
    "M2StageWorldLineageRecord",
    "M2StageWorldLineageSummary",
    "M3FamilyApplicabilityContract",
    "M3MissionProductApplicability",
    "M3MissionProductApplicabilityError",
    "M3MissionProductInputSet",
    "M3MissionSystemSubject",
    "M3ProfileEpisode",
    "M3ProfileProjection",
    "M3ProfileStage",
    "M3ProfileStageEvent",
    "M3ProfileWorldError",
    "M3WVREpisode",
    "M3WVRProjection",
    "M3WVRStage",
    "M3WVRStageEvent",
    "M3WVRWorldError",
    "M8EvidenceRef",
    "M8WorldFactRef",
    "P4InteractionScopeSnapshot",
    "P5CompositionSnapshot",
    "P5ParticipantBinding",
    "WorldEvidenceRef",
    "WorldProjectionError",
    "assert_composition_identity",
    "assert_world_facts_immutable",
    "build_m2_radar_sensor_world",
    "build_m2_reference_time_world",
    "build_m2_stage_world_lineage",
    "build_p4_interaction_scope_snapshot",
    "build_p5_composition_snapshot",
    "load_m3_mission_product_inputs",
    "project_m2_radar_sensor_world",
    "project_m2_reference_time_world",
    "project_m2_stage_world_lineage",
    "project_m3_family_applicability",
    "project_m3_training_profile",
    "project_m3_wvr_world",
    "project_minimal_p1_world",
]
