"""P3 capability-model and aircraft-twin domain services."""

from .p3_model import (
    P3CapabilityModelBuild,
    P3CapabilityModelProduct,
    P3CapabilitySurfaceBuild,
    P3CapabilitySurfaceProduct,
    P3ModelExecutionProfile,
    P3ModelValidationResult,
    P3SurfaceEvaluation,
    P3TrainingDatasetSnapshot,
    build_capability_surface,
    evaluate_surface,
    evaluate_temporal_holdout,
    execute_capability_model,
    materialize_training_dataset,
)
from .p3_twin import (
    P3AircraftTwinRevision,
    P3CapabilityEstimate,
    P3TwinComponentBinding,
    evaluate_twin_capability_estimate,
    publish_aircraft_twin_revision,
)
from .p6_input import (
    P6ContextRef,
    P6CounterfactualRequestBinding,
    P6FactualSourceRevision,
    P6ForecastRequestBinding,
    P6InputSnapshot,
    P6P3ModelRef,
    assert_p6_input_snapshot_identity,
    build_p6_counterfactual_request_binding,
    build_p6_forecast_request_binding,
    build_p6_input_snapshot,
)

__all__ = [
    "P3CapabilityModelBuild",
    "P3CapabilityModelProduct",
    "P3CapabilitySurfaceBuild",
    "P3CapabilitySurfaceProduct",
    "P3ModelExecutionProfile",
    "P3ModelValidationResult",
    "P3SurfaceEvaluation",
    "P3TrainingDatasetSnapshot",
    "P3AircraftTwinRevision",
    "P3CapabilityEstimate",
    "P3TwinComponentBinding",
    "P6ContextRef",
    "P6CounterfactualRequestBinding",
    "P6FactualSourceRevision",
    "P6ForecastRequestBinding",
    "P6InputSnapshot",
    "P6P3ModelRef",
    "assert_p6_input_snapshot_identity",
    "build_p6_counterfactual_request_binding",
    "build_p6_forecast_request_binding",
    "build_capability_surface",
    "build_p6_input_snapshot",
    "evaluate_surface",
    "evaluate_temporal_holdout",
    "execute_capability_model",
    "materialize_training_dataset",
    "evaluate_twin_capability_estimate",
    "publish_aircraft_twin_revision",
]
