# @generated by TPAA codegen; DO NOT EDIT BY HAND.
# generator_id=generated-package-init
# generator_version=0.2.0
# source artifact_id=BASELINE_LOCK version=CB-1.4.0 sha256=a55ccc5f75d128c4dc3c3208064596eeb2dda7ffaf340d87726a22d4b62f93c6
"""Deterministically generated TPAA projections. Do not edit by hand."""
