# @generated by TPAA codegen; DO NOT EDIT BY HAND.
# generator_id=generated-package-init
# generator_version=0.2.0
# source artifact_id=BASELINE_LOCK version=CB-1.4.0 sha256=7eafadbb1d47297688595a8a0c48d4836dad13e040f76340ce2c0fa38a5547fa
"""Deterministically generated TPAA projections. Do not edit by hand."""
