# @generated by TPAA codegen; DO NOT EDIT BY HAND.
# generator_id=baseline-metadata
# generator_version=0.2.0
# source artifact_id=BASELINE_LOCK version=CB-1.4.0 sha256=2852dc2904854fcd65e3207ddda4859795b003e839ff1d95e241b199879ddd1f
"""Generated TPAA baseline metadata. Do not edit by hand."""

CORE_BASELINE = 'CB-1.4.0'
DB_SCHEMA_VERSION = '1.6.0'
BASELINE_LOCK_SHA256 = '2852dc2904854fcd65e3207ddda4859795b003e839ff1d95e241b199879ddd1f'
