# @generated by TPAA codegen; DO NOT EDIT BY HAND.
# generator_id=baseline-metadata
# generator_version=0.2.0
# source artifact_id=BASELINE_LOCK version=CB-1.4.0 sha256=d6ebab2b5402cf81a0b5f73a2da4ed2aaa2d530bc7445c7f6132dcf7fa72224d
"""Generated TPAA baseline metadata. Do not edit by hand."""

CORE_BASELINE = 'CB-1.4.0'
DB_SCHEMA_VERSION = '1.6.0'
BASELINE_LOCK_SHA256 = 'd6ebab2b5402cf81a0b5f73a2da4ed2aaa2d530bc7445c7f6132dcf7fa72224d'
