# @generated by TPAA codegen; DO NOT EDIT BY HAND.
# generator_id=baseline-metadata
# generator_version=0.2.0
# source artifact_id=BASELINE_LOCK version=CB-1.4.0 sha256=9d96a7eb0ba2b1fb13b11d76943171f773fd42497df74bf79c01928cfa26e7fa
"""Generated TPAA baseline metadata. Do not edit by hand."""

CORE_BASELINE = 'CB-1.4.0'
DB_SCHEMA_VERSION = '1.6.0'
BASELINE_LOCK_SHA256 = '9d96a7eb0ba2b1fb13b11d76943171f773fd42497df74bf79c01928cfa26e7fa'
