"""Generated TPAA cross-layer DTO transport types. Do not edit by hand."""

from __future__ import annotations

from typing import NotRequired, Required, TypeAlias, TypedDict

JSONScalar: TypeAlias = str | int | float | bool | None
JSONValue: TypeAlias = JSONScalar | list['JSONValue'] | dict[str, 'JSONValue']

class CapabilityObservationDTO(TypedDict, total=False):
    aircraft_configuration_snapshot_id: NotRequired[str | None]
    aircraft_id: Required[str]
    aircraft_instance_id: Required[str]
    aircraft_model_id: Required[str]
    capability_dimension: Required[str]
    capability_level: Required[str]
    capability_type: Required[str]
    comparison_key_hash: Required[str]
    confidence: Required[int | float]
    context_id: Required[str]
    context_tags: Required[dict[str, JSONValue]]
    correlation_group_id: NotRequired[str | None]
    coverage: Required[int | float]
    eligibility_status: Required[str]
    episode_id: Required[str]
    evidence_set_id: Required[str]
    exclusion_reason_code: NotRequired[str | None]
    metric_code: Required[str]
    metric_semantic_id: Required[str]
    metric_semantic_version: Required[int]
    observation_end_session_time_us: Required[str]
    observation_id: Required[str]
    observation_schema_version: Required[str]
    observation_start_session_time_us: Required[str]
    observed_metric_instance_id: Required[str]
    pilot_id: NotRequired[str | None]
    release_id: Required[str]
    scenario_id: NotRequired[str | None]
    session_id: Required[str]
    stage_id: NotRequired[str | None]
    structured_output_schema_id: NotRequired[str | None]
    subject_entity_id: Required[str]
    supersedes_observation_id: NotRequired[str | None]
    unit: Required[str]
    value: NotRequired[JSONValue]
    value_kind: Required[str]

class ContextArtifactRefDTO(TypedDict, total=False):
    binding_role: Required[str]
    context_artifact_id: Required[str]
    artifact_kind: Required[str]
    logical_key: Required[str]
    artifact_version: Required[str]
    object_ref_id: Required[str]
    artifact_sha256: Required[str]
    schema_version: Required[str]

class EvaluationContextBundleDTO(TypedDict, total=False):
    context: Required[EvaluationContextDTO]
    artifact_refs: Required[list[ContextArtifactRefDTO]]
    scenario: NotRequired[dict[str, JSONValue] | None]
    assessment_profile: NotRequired[dict[str, JSONValue] | None]
    objectives: Required[list[dict[str, JSONValue]]]
    roles: Required[list[dict[str, JSONValue]]]
    stages: Required[list[dict[str, JSONValue]]]
    references: Required[list[dict[str, JSONValue]]]
    rules: Required[list[dict[str, JSONValue]]]
    cohort: Required[list[dict[str, JSONValue]]]

class EvaluationContextDTO(TypedDict, total=False):
    context_id: Required[str]
    session_id: Required[str]
    context_version: Required[str]
    revision_no: Required[int]
    supersedes_context_id: NotRequired[str | None]
    scenario_id: NotRequired[str | None]
    scenario_version: NotRequired[str | None]
    syllabus_id: NotRequired[str | None]
    syllabus_version: NotRequired[str | None]
    assessment_profile_id: NotRequired[str | None]
    assessment_profile_version: NotRequired[str | None]
    rule_set_version: Required[str]
    reference_set_version: NotRequired[str | None]
    role_model_version: NotRequired[str | None]
    metric_profile_version: Required[str]
    longitudinal_profile_version: NotRequired[str | None]
    valid_from_session_time_us: NotRequired[str | None]
    valid_to_session_time_us: NotRequired[str | None]
    status: Required[str]

class MetricCatalogEntryDTO(TypedDict, total=False):
    metric_code: Required[str]
    semantic_id: Required[str]
    semantic_version: Required[int]
    algorithm_id: Required[str]
    algorithm_version: Required[str]
    family: Required[str]
    subject_type: Required[str]
    observation_lane: Required[str]
    publication_route: Required[str]
    value_kind: Required[str]
    structured_output_schema_id: NotRequired[str | None]
    unit: Required[str]
    delivery_milestone: Required[str]
    delivery_batch: Required[str]
    p1_longitudinal_trend_eligibility: Required[bool]
    default_aggregation: Required[str]
    operator_bindings: Required[list[str]]
    constant_bindings: Required[list[str]]
    upstream_dependencies: Required[list[str]]
    state_machine_bindings: Required[list[str]]
    profile_parameters: Required[list[str]]
    input_fields: Required[list[str]]
    catalog_version: Required[str]

class MissionSystemObservationDTO(TypedDict, total=False):
    system_observation_id: Required[str]
    release_id: Required[str]
    session_id: Required[str]
    episode_id: NotRequired[str | None]
    stage_id: NotRequired[str | None]
    aircraft_id: Required[str]
    mission_system_instance_id: Required[str]
    observed_metric_instance_id: Required[str]
    reference_truth_profile_version: NotRequired[str | None]
    reference_quality_status: Required[str]
    reference_uncertainty_summary: Required[dict[str, JSONValue]]
    alignment_uncertainty_summary: Required[dict[str, JSONValue]]
    observation_start_session_time_us: Required[str]
    observation_end_session_time_us: Required[str]
    context_tags: Required[dict[str, JSONValue]]
    evidence_set_id: Required[str]
    coverage: Required[int | float]
    confidence: Required[int | float]
    eligibility_status: Required[str]
    exclusion_reason_code: NotRequired[str | None]
    comparison_key_hash: Required[str]
    observation_schema_version: Required[str]
    supersedes_system_observation_id: NotRequired[str | None]

class TPAAChainDTO(TypedDict, total=False):
    chain_id: Required[str]
    release_id: Required[str]
    episode_id: Required[str]
    stage_id: NotRequired[str | None]
    refs: Required[dict[str, JSONValue]]
    start_session_time_us: Required[str]
    end_session_time_us: Required[str]
    chain_status: Required[str]
    coverage: Required[int | float]
    confidence: Required[int | float]
    break_reason: NotRequired[str | None]
    chain_version: Required[str]
