"""Generated TPAA P1 Metric identity/metadata registry. Do not edit by hand."""

from enum import StrEnum
from types import MappingProxyType
from typing import Mapping

class P1MetricCode(StrEnum):
    P1_AIR_001 = 'P1-AIR-001'
    P1_AIR_002 = 'P1-AIR-002'
    P1_AIR_003 = 'P1-AIR-003'
    P1_AIR_004 = 'P1-AIR-004'
    P1_AIR_005 = 'P1-AIR-005'
    P1_AIR_006 = 'P1-AIR-006'
    P1_AIR_007 = 'P1-AIR-007'
    P1_AIR_008 = 'P1-AIR-008'
    P1_AIR_009 = 'P1-AIR-009'
    P1_AIR_010 = 'P1-AIR-010'
    P1_AIR_011 = 'P1-AIR-011'
    P1_AIR_012 = 'P1-AIR-012'
    P1_AIR_013 = 'P1-AIR-013'
    P1_AIR_014 = 'P1-AIR-014'
    P1_AIR_015 = 'P1-AIR-015'
    P1_AIR_016 = 'P1-AIR-016'
    P1_AIR_017 = 'P1-AIR-017'
    P1_AIR_018 = 'P1-AIR-018'
    P1_AIR_019 = 'P1-AIR-019'
    P1_AIR_020 = 'P1-AIR-020'
    P1_AIR_021 = 'P1-AIR-021'
    P1_AIR_022 = 'P1-AIR-022'
    P1_AIR_023 = 'P1-AIR-023'
    P1_AIR_024 = 'P1-AIR-024'
    P1_AIR_025 = 'P1-AIR-025'
    P1_AIR_026 = 'P1-AIR-026'
    P1_AIR_027 = 'P1-AIR-027'
    P1_AIR_028 = 'P1-AIR-028'
    P1_AIR_029 = 'P1-AIR-029'
    P1_AIR_030 = 'P1-AIR-030'
    P1_AIR_031 = 'P1-AIR-031'
    P1_AIR_032 = 'P1-AIR-032'
    P1_AIR_033 = 'P1-AIR-033'
    P1_AIR_034 = 'P1-AIR-034'
    P1_AIR_035 = 'P1-AIR-035'
    P1_AIR_036 = 'P1-AIR-036'
    P1_AIR_037 = 'P1-AIR-037'
    P1_AIR_038 = 'P1-AIR-038'
    P1_AIR_039 = 'P1-AIR-039'
    P1_DL_001 = 'P1-DL-001'
    P1_DL_002 = 'P1-DL-002'
    P1_DL_003 = 'P1-DL-003'
    P1_DL_004 = 'P1-DL-004'
    P1_DL_005 = 'P1-DL-005'
    P1_DL_006 = 'P1-DL-006'
    P1_DL_007 = 'P1-DL-007'
    P1_DL_008 = 'P1-DL-008'
    P1_ESM_001 = 'P1-ESM-001'
    P1_ESM_002 = 'P1-ESM-002'
    P1_ESM_003 = 'P1-ESM-003'
    P1_ESM_004 = 'P1-ESM-004'
    P1_ESM_005 = 'P1-ESM-005'
    P1_ESM_006 = 'P1-ESM-006'
    P1_FUS_001 = 'P1-FUS-001'
    P1_FUS_002 = 'P1-FUS-002'
    P1_FUS_003 = 'P1-FUS-003'
    P1_FUS_004 = 'P1-FUS-004'
    P1_FUS_005 = 'P1-FUS-005'
    P1_FUS_006 = 'P1-FUS-006'
    P1_FUS_007 = 'P1-FUS-007'
    P1_FUS_008 = 'P1-FUS-008'
    P1_ID_001 = 'P1-ID-001'
    P1_ID_002 = 'P1-ID-002'
    P1_ID_003 = 'P1-ID-003'
    P1_ID_004 = 'P1-ID-004'
    P1_ID_005 = 'P1-ID-005'
    P1_ID_006 = 'P1-ID-006'
    P1_ID_007 = 'P1-ID-007'
    P1_ID_008 = 'P1-ID-008'
    P1_ID_009 = 'P1-ID-009'
    P1_ID_010 = 'P1-ID-010'
    P1_ID_011 = 'P1-ID-011'
    P1_ID_012 = 'P1-ID-012'
    P1_PSV_001 = 'P1-PSV-001'
    P1_PSV_002 = 'P1-PSV-002'
    P1_PSV_003 = 'P1-PSV-003'
    P1_PSV_004 = 'P1-PSV-004'
    P1_PSV_005 = 'P1-PSV-005'
    P1_PSV_006 = 'P1-PSV-006'
    P1_PSV_007 = 'P1-PSV-007'
    P1_QA_001 = 'P1-QA-001'
    P1_QA_002 = 'P1-QA-002'
    P1_QA_003 = 'P1-QA-003'
    P1_QA_004 = 'P1-QA-004'
    P1_QA_005 = 'P1-QA-005'
    P1_QA_006 = 'P1-QA-006'
    P1_QA_007 = 'P1-QA-007'
    P1_QA_008 = 'P1-QA-008'
    P1_SNS_001 = 'P1-SNS-001'
    P1_SNS_002 = 'P1-SNS-002'
    P1_SNS_003 = 'P1-SNS-003'
    P1_SNS_004 = 'P1-SNS-004'
    P1_SNS_005 = 'P1-SNS-005'
    P1_SNS_006 = 'P1-SNS-006'
    P1_SNS_007 = 'P1-SNS-007'
    P1_SNS_008 = 'P1-SNS-008'
    P1_SNS_009 = 'P1-SNS-009'
    P1_SNS_010 = 'P1-SNS-010'
    P1_SNS_011 = 'P1-SNS-011'
    P1_SNS_012 = 'P1-SNS-012'
    P1_SNS_013 = 'P1-SNS-013'
    P1_SNS_014 = 'P1-SNS-014'
    P1_SNS_015 = 'P1-SNS-015'
    P1_SNS_016 = 'P1-SNS-016'
    P1_SNS_017 = 'P1-SNS-017'
    P1_SNS_018 = 'P1-SNS-018'
    P1_SNS_019 = 'P1-SNS-019'
    P1_SNS_020 = 'P1-SNS-020'
    P1_SNS_021 = 'P1-SNS-021'
    P1_TRK_001 = 'P1-TRK-001'
    P1_TRK_002 = 'P1-TRK-002'
    P1_TRK_003 = 'P1-TRK-003'
    P1_TRK_004 = 'P1-TRK-004'
    P1_TRK_005 = 'P1-TRK-005'
    P1_TRK_006 = 'P1-TRK-006'
    P1_TRK_007 = 'P1-TRK-007'

P1_METRICS: tuple[Mapping[str, object], ...] = (
    MappingProxyType({
        'metric_code': 'P1-AIR-001',
        'name': 'MAX_ABS_BODY_ROLL_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.max_abs_body_roll_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.max_abs_body_roll_rate',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-002',
        'name': 'MAX_NZ_OBSERVED',
        'semantic_id': 'tpaa.p1.air.max_nz',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'g',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.max_nz',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-003',
        'name': 'TRUE_HEADING_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.true_heading_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.true_heading_rate',
        'algorithm_version': '1.0.0',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-004',
        'name': 'SUSTAINED_TRUE_HEADING_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.sustained_true_heading_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.sustained_true_heading_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-005',
        'name': 'HORIZONTAL_TURN_RADIUS_OBSERVED',
        'semantic_id': 'tpaa.p1.air.horizontal_turn_radius',
        'semantic_version': 2,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.horizontal_turn_radius',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-006',
        'name': 'SUSTAINED_NZ_OBSERVED',
        'semantic_id': 'tpaa.p1.air.sustained_nz',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'g',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.sustained_nz',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-007',
        'name': 'TAS_MACH_ENVELOPE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.tas_mach_envelope',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.tas_mach_envelope',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_007_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-008',
        'name': 'MAX_ACCELERATION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.max_tas_acceleration',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s^2',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.max_tas_acceleration',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-009',
        'name': 'SUSTAINED_ACCELERATION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.sustained_tas_acceleration',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s^2',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.sustained_tas_acceleration',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-010',
        'name': 'ACCELERATION_TIME_BAND_OBSERVED',
        'semantic_id': 'tpaa.p1.air.acceleration_time_band',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.acceleration_time_band',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-011',
        'name': 'MAX_DECELERATION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.max_tas_deceleration',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s^2',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.max_tas_deceleration',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-012',
        'name': 'DECELERATION_TIME_BAND_OBSERVED',
        'semantic_id': 'tpaa.p1.air.deceleration_time_band',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.deceleration_time_band',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-013',
        'name': 'MAX_CLIMB_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.max_climb_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.max_climb_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-014',
        'name': 'SUSTAINED_CLIMB_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.sustained_climb_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.sustained_climb_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-015',
        'name': 'DIVE_ACCELERATION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.dive_acceleration',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s^2',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.dive_acceleration',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-016',
        'name': 'SPECIFIC_MECHANICAL_ENERGY_OBSERVED',
        'semantic_id': 'tpaa.p1.air.specific_mechanical_energy',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'J/kg',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.specific_mechanical_energy',
        'algorithm_version': '1.0.0',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-017',
        'name': 'SPECIFIC_ENERGY_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.specific_energy_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'W/kg',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.specific_energy_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-018',
        'name': 'SPECIFIC_EXCESS_POWER_OBSERVED',
        'semantic_id': 'tpaa.p1.air.specific_excess_power_observed',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.specific_excess_power_observed',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-019',
        'name': 'ENERGY_RETENTION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.energy_retention',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.energy_retention',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_019_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-020',
        'name': 'ENERGY_RECOVERY_TIME_OBSERVED',
        'semantic_id': 'tpaa.p1.air.energy_recovery_time',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.energy_recovery_time',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-021',
        'name': 'ENERGY_RECOVERY_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.energy_recovery_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'W/kg',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.energy_recovery_rate',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-022',
        'name': 'SUSTAINED_ROLL_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.sustained_body_roll_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.sustained_body_roll_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-023',
        'name': 'ROLL_TO_BANK_TIME_OBSERVED',
        'semantic_id': 'tpaa.p1.air.roll_to_bank_time',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.roll_to_bank_time',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-024',
        'name': 'NOSE_POINTING_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.nose_pointing_rate',
        'semantic_version': 2,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.nose_pointing_rate',
        'algorithm_version': '2.0.0',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-025',
        'name': 'AOA_ENVELOPE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.aoa_envelope',
        'semantic_version': 2,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.aoa_envelope',
        'algorithm_version': '2.0.0',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_025_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-026',
        'name': 'HIGH_AOA_DWELL_OBSERVED',
        'semantic_id': 'tpaa.p1.air.high_aoa_dwell',
        'semantic_version': 1,
        'family': 'AIRCRAFT_FLIGHT',
        'subject_type': 'AIRCRAFT',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.high_aoa_dwell',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-027',
        'name': 'CONTROL_RESPONSE_DELAY_OBSERVED',
        'semantic_id': 'tpaa.p1.air.control_response_delay',
        'semantic_version': 1,
        'family': 'AIRCRAFT_CONTROL_RESPONSE',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.control_response_delay',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-028',
        'name': 'CONTROL_INPUT_RATE_RMS',
        'semantic_id': 'tpaa.p1.air.control_input_rate_rms',
        'semantic_version': 1,
        'family': 'AIRCRAFT_HANDLING',
        'subject_type': 'AIRCRAFT',
        'unit': 'normalized/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.control_input_rate_rms',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-029',
        'name': 'CONTROL_REVERSAL_COUNT',
        'semantic_id': 'tpaa.p1.air.control_reversal_count',
        'semantic_version': 1,
        'family': 'AIRCRAFT_HANDLING',
        'subject_type': 'AIRCRAFT',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.control_reversal_count',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-030',
        'name': 'ATTITUDE_OSCILLATION_INDEX',
        'semantic_id': 'tpaa.p1.air.attitude_oscillation_index',
        'semantic_version': 1,
        'family': 'AIRCRAFT_HANDLING',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.attitude_oscillation_index',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_030_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-031',
        'name': 'JERK_RMS',
        'semantic_id': 'tpaa.p1.air.jerk_rms',
        'semantic_version': 2,
        'family': 'AIRCRAFT_HANDLING',
        'subject_type': 'AIRCRAFT',
        'unit': 'm/s^3',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.jerk_rms',
        'algorithm_version': '2.0.0',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-032',
        'name': 'FUEL_FLOW_OBSERVED',
        'semantic_id': 'tpaa.p1.air.fuel_flow',
        'semantic_version': 2,
        'family': 'AIRCRAFT_PERSISTENCE',
        'subject_type': 'AIRCRAFT',
        'unit': 'kg/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.fuel_flow',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-033',
        'name': 'FUEL_BURN_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.fuel_burn_rate',
        'semantic_version': 1,
        'family': 'AIRCRAFT_PERSISTENCE',
        'subject_type': 'AIRCRAFT',
        'unit': 'kg/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.fuel_burn_rate',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-034',
        'name': 'ENDURANCE_PROXY_OBSERVED',
        'semantic_id': 'tpaa.p1.air.endurance_proxy',
        'semantic_version': 1,
        'family': 'AIRCRAFT_PERSISTENCE',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.endurance_proxy',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-035',
        'name': 'CONTROL_RESPONSE_GAIN_OBSERVED',
        'semantic_id': 'tpaa.p1.air.control_response_gain',
        'semantic_version': 1,
        'family': 'AIRCRAFT_CONTROL_RESPONSE',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.control_response_gain',
        'algorithm_version': '1.0.5',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_035_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-036',
        'name': 'CONTROL_DEADBAND_OBSERVED',
        'semantic_id': 'tpaa.p1.air.control_deadband',
        'semantic_version': 1,
        'family': 'AIRCRAFT_CONTROL_RESPONSE',
        'subject_type': 'AIRCRAFT',
        'unit': 'normalized',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.control_deadband',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-037',
        'name': 'RESPONSE_PERSISTENCE_OBSERVED',
        'semantic_id': 'tpaa.p1.air.response_persistence',
        'semantic_version': 2,
        'family': 'AIRCRAFT_CONTROL_RESPONSE',
        'subject_type': 'AIRCRAFT',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.response_persistence',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-038',
        'name': 'CLIMB_ENERGY_PARTITION_OBSERVED',
        'semantic_id': 'tpaa.p1.air.climb_energy_partition',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.air.climb_energy_partition',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-AIR-039',
        'name': 'DIVE_ENERGY_GAIN_OBSERVED',
        'semantic_id': 'tpaa.p1.air.dive_energy_gain',
        'semantic_version': 1,
        'family': 'AIRCRAFT_ENERGY',
        'subject_type': 'AIRCRAFT',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.air.dive_energy_gain',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'AIRCRAFT_CAP_L1_OBSERVATION',
        'publication_route': 'CAPABILITY_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_AIR_039_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-001',
        'name': 'MESSAGE_LATENCY',
        'semantic_id': 'tpaa.p1.datalink.message_latency',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.message_latency',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-002',
        'name': 'MESSAGE_JITTER',
        'semantic_id': 'tpaa.p1.datalink.message_jitter',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.message_jitter',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-003',
        'name': 'MESSAGE_LOSS_RATE',
        'semantic_id': 'tpaa.p1.datalink.message_loss_rate',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.message_loss_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-004',
        'name': 'OUT_OF_ORDER_RATE',
        'semantic_id': 'tpaa.p1.datalink.out_of_order_rate',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.out_of_order_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-005',
        'name': 'REMOTE_TRACK_AGE',
        'semantic_id': 'tpaa.p1.datalink.remote_track_age',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.remote_track_age',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-006',
        'name': 'REMOTE_TRACK_POSITION_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.datalink.remote_track_position_error_rmse',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.remote_track_position_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-007',
        'name': 'REMOTE_TRACK_VELOCITY_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.datalink.remote_track_velocity_error_rmse',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.remote_track_velocity_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-DL-008',
        'name': 'REMOTE_TRACK_CONTINUITY',
        'semantic_id': 'tpaa.p1.datalink.remote_track_continuity',
        'semantic_version': 1,
        'family': 'DATALINK',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.datalink.remote_track_continuity',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-001',
        'name': 'EMITTER_DETECTION_RATE',
        'semantic_id': 'tpaa.p1.esm.emitter_detection_rate',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_detection_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-002',
        'name': 'EMITTER_BEARING_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.esm.emitter_bearing_error_rmse',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_bearing_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-003',
        'name': 'EMITTER_DETECTION_LATENCY',
        'semantic_id': 'tpaa.p1.esm.emitter_detection_latency',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_detection_latency',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-004',
        'name': 'EMITTER_ASSOCIATION_ACCURACY',
        'semantic_id': 'tpaa.p1.esm.emitter_association_accuracy',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_association_accuracy',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-005',
        'name': 'EMITTER_CLASSIFICATION_ACCURACY',
        'semantic_id': 'tpaa.p1.esm.emitter_classification_accuracy',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_classification_accuracy',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ESM-006',
        'name': 'EMITTER_TRACK_CONTINUITY',
        'semantic_id': 'tpaa.p1.esm.emitter_track_continuity',
        'semantic_version': 1,
        'family': 'RWR_ESM',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.esm.emitter_track_continuity',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-001',
        'name': 'FUSED_POSITION_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.fusion.position_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.position_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-002',
        'name': 'FUSED_VELOCITY_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.fusion.velocity_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.velocity_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-003',
        'name': 'FUSION_LATENCY',
        'semantic_id': 'tpaa.p1.fusion.latency',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.latency',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-004',
        'name': 'FUSED_TRACK_CONTINUITY',
        'semantic_id': 'tpaa.p1.fusion.track_continuity',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.track_continuity',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-005',
        'name': 'DUPLICATE_SUPPRESSION_RATE',
        'semantic_id': 'tpaa.p1.fusion.duplicate_suppression_rate',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.duplicate_suppression_rate',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-006',
        'name': 'FUSION_ASSOCIATION_ACCURACY',
        'semantic_id': 'tpaa.p1.fusion.association_accuracy',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.association_accuracy',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-007',
        'name': 'TRACK_HANDOVER_CONTINUITY',
        'semantic_id': 'tpaa.p1.fusion.handover_continuity',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.handover_continuity',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-FUS-008',
        'name': 'TRACK_HANDOVER_JUMP',
        'semantic_id': 'tpaa.p1.fusion.handover_jump',
        'semantic_version': 1,
        'family': 'SENSOR_FUSION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.fusion.handover_jump',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-001',
        'name': 'ASSOCIATION_ACCURACY',
        'semantic_id': 'tpaa.p1.id.association_accuracy',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.association_accuracy',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-002',
        'name': 'WRONG_ASSOCIATION_COUNT',
        'semantic_id': 'tpaa.p1.id.wrong_association_count',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.wrong_association_count',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-003',
        'name': 'TRACK_SWAP_COUNT',
        'semantic_id': 'tpaa.p1.id.track_swap_count',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.track_swap_count',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-004',
        'name': 'TRACK_SPLIT_COUNT',
        'semantic_id': 'tpaa.p1.id.track_split_count',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.track_split_count',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-005',
        'name': 'TRACK_MERGE_COUNT',
        'semantic_id': 'tpaa.p1.id.track_merge_count',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.track_merge_count',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-006',
        'name': 'DUPLICATE_TRACK_RATIO',
        'semantic_id': 'tpaa.p1.id.duplicate_track_ratio',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.duplicate_track_ratio',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-007',
        'name': 'TRACK_IDENTITY_CONTINUITY',
        'semantic_id': 'tpaa.p1.id.track_identity_continuity',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.track_identity_continuity',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-008',
        'name': 'IDENTIFICATION_ACCURACY',
        'semantic_id': 'tpaa.p1.id.identification_accuracy',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.identification_accuracy',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-009',
        'name': 'FALSE_IDENTIFICATION_RATE',
        'semantic_id': 'tpaa.p1.id.false_identification_rate',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.false_identification_rate',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-010',
        'name': 'UNKNOWN_DWELL_RATIO',
        'semantic_id': 'tpaa.p1.id.unknown_dwell_ratio',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.unknown_dwell_ratio',
        'algorithm_version': '1.0.1',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-011',
        'name': 'IDENTIFICATION_LATENCY',
        'semantic_id': 'tpaa.p1.id.identification_latency',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.identification_latency',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-ID-012',
        'name': 'IDENTIFICATION_STABILITY',
        'semantic_id': 'tpaa.p1.id.identification_stability',
        'semantic_version': 1,
        'family': 'ASSOCIATION_IDENTIFICATION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.id.identification_stability',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-001',
        'name': 'PASSIVE_LOS_ANGULAR_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.passive.los_angular_error_rmse',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.los_angular_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-002',
        'name': 'PASSIVE_LOS_RATE_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.passive.los_rate_error_rmse',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.los_rate_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-003',
        'name': 'PASSIVE_RANGE_ESTIMATE_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.passive.range_estimate_error_rmse',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.range_estimate_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-004',
        'name': 'PASSIVE_DETECTION_RATE',
        'semantic_id': 'tpaa.p1.passive.detection_rate',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.detection_rate',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-005',
        'name': 'PASSIVE_TRACK_CONTINUITY',
        'semantic_id': 'tpaa.p1.passive.track_continuity',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.track_continuity',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-006',
        'name': 'PASSIVE_REACQUISITION_TIME',
        'semantic_id': 'tpaa.p1.passive.reacquisition_time',
        'semantic_version': 2,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.reacquisition_time',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-PSV-007',
        'name': 'PASSIVE_FALSE_TRACK_RATE',
        'semantic_id': 'tpaa.p1.passive.false_track_rate',
        'semantic_version': 1,
        'family': 'PASSIVE_SENSOR',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.passive.false_track_rate',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-001',
        'name': 'REFERENCE_RELATIVE_STATE',
        'semantic_id': 'tpaa.p1.qa.reference_relative_state',
        'semantic_version': 1,
        'family': 'REFERENCE_TRUTH',
        'subject_type': 'TARGET_PAIR',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.qa.reference_relative_state',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'QUALITY_EVIDENCE_ONLY',
        'publication_route': 'METRIC_INSTANCE_EVIDENCE_ONLY',
        'structured_output_schema_id': 'STRUCT_P1_QA_001_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-002',
        'name': 'REFERENCE_TRUTH_UNCERTAINTY',
        'semantic_id': 'tpaa.p1.qa.reference_truth_uncertainty',
        'semantic_version': 1,
        'family': 'REFERENCE_TRUTH',
        'subject_type': 'TARGET_PAIR',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.qa.reference_truth_uncertainty',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'QUALITY_EVIDENCE_ONLY',
        'publication_route': 'METRIC_INSTANCE_EVIDENCE_ONLY',
        'structured_output_schema_id': 'STRUCT_P1_QA_002_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-003',
        'name': 'SENSOR_TIME_OFFSET_OBSERVED',
        'semantic_id': 'tpaa.p1.qa.sensor_time_offset',
        'semantic_version': 2,
        'family': 'TIME_ALIGNMENT',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'us',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.qa.sensor_time_offset',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-004',
        'name': 'SENSOR_TO_INS_LATENCY_OBSERVED',
        'semantic_id': 'tpaa.p1.qa.sensor_to_ins_latency',
        'semantic_version': 2,
        'family': 'TIME_ALIGNMENT',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'us',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.qa.sensor_to_ins_latency',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-005',
        'name': 'INTERPOLATION_AGE_OBSERVED',
        'semantic_id': 'tpaa.p1.qa.interpolation_age',
        'semantic_version': 2,
        'family': 'TIME_ALIGNMENT',
        'subject_type': 'TARGET_PAIR',
        'unit': 'us',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.qa.interpolation_age',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'QUALITY_EVIDENCE_ONLY',
        'publication_route': 'METRIC_INSTANCE_EVIDENCE_ONLY',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-006',
        'name': 'MEASUREMENT_ERROR_DECOMPOSITION',
        'semantic_id': 'tpaa.p1.qa.measurement_error_decomposition',
        'semantic_version': 1,
        'family': 'REFERENCE_TRUTH',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'STRUCTURED',
        'value_kind': 'STRUCTURED',
        'algorithm_id': 'alg.tpaa.p1.qa.measurement_error_decomposition',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': 'STRUCT_P1_QA_006_V1',
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-007',
        'name': 'OWNSHIP_INS_TIME_UNCERTAINTY',
        'semantic_id': 'tpaa.p1.qa.ownship_ins_time_uncertainty',
        'semantic_version': 1,
        'family': 'TIME_ALIGNMENT',
        'subject_type': 'AIRCRAFT',
        'unit': 'us',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.qa.ownship_ins_time_uncertainty',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'QUALITY_EVIDENCE_ONLY',
        'publication_route': 'METRIC_INSTANCE_EVIDENCE_ONLY',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-QA-008',
        'name': 'TARGET_INS_TIME_UNCERTAINTY',
        'semantic_id': 'tpaa.p1.qa.target_ins_time_uncertainty',
        'semantic_version': 1,
        'family': 'TIME_ALIGNMENT',
        'subject_type': 'TARGET_PAIR',
        'unit': 'us',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.qa.target_ins_time_uncertainty',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'QUALITY_EVIDENCE_ONLY',
        'publication_route': 'METRIC_INSTANCE_EVIDENCE_ONLY',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': False,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-001',
        'name': 'DETECTION_OPPORTUNITY_COVERAGE',
        'semantic_id': 'tpaa.p1.sensor.detection_opportunity_coverage',
        'semantic_version': 1,
        'family': 'SENSOR_DETECTION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.detection_opportunity_coverage',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-002',
        'name': 'DETECTION_RATE_OBSERVED',
        'semantic_id': 'tpaa.p1.sensor.detection_rate',
        'semantic_version': 1,
        'family': 'SENSOR_DETECTION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.detection_rate',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-003',
        'name': 'TIME_TO_FIRST_DETECTION',
        'semantic_id': 'tpaa.p1.sensor.time_to_first_detection',
        'semantic_version': 1,
        'family': 'SENSOR_DETECTION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.time_to_first_detection',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-004',
        'name': 'FIRST_DETECTION_RANGE_OBSERVED',
        'semantic_id': 'tpaa.p1.sensor.first_detection_range',
        'semantic_version': 1,
        'family': 'SENSOR_DETECTION',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.first_detection_range',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-005',
        'name': 'RANGE_ERROR_BIAS',
        'semantic_id': 'tpaa.p1.sensor.range_error_bias',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_bias',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-006',
        'name': 'RANGE_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.range_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-007',
        'name': 'RANGE_ERROR_P95',
        'semantic_id': 'tpaa.p1.sensor.range_error_p95',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_p95',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-008',
        'name': 'AZIMUTH_ERROR_BIAS',
        'semantic_id': 'tpaa.p1.sensor.azimuth_error_bias',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.azimuth_error_bias',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-009',
        'name': 'AZIMUTH_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.azimuth_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.azimuth_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-010',
        'name': 'ELEVATION_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.elevation_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.elevation_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-011',
        'name': 'POSITION_3D_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.position_3d_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.position_3d_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-012',
        'name': 'RADIAL_VELOCITY_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.radial_velocity_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.radial_velocity_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-013',
        'name': 'CROSS_RANGE_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.cross_range_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.cross_range_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-014',
        'name': 'VERTICAL_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.vertical_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.vertical_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-015',
        'name': 'RANGE_ERROR_MAE',
        'semantic_id': 'tpaa.p1.sensor.range_error_mae',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_mae',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-016',
        'name': 'RANGE_ERROR_P50',
        'semantic_id': 'tpaa.p1.sensor.range_error_p50',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_p50',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-017',
        'name': 'RANGE_ERROR_MAX_ABS',
        'semantic_id': 'tpaa.p1.sensor.range_error_max_abs',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.range_error_max_abs',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-018',
        'name': 'AZIMUTH_ERROR_P95',
        'semantic_id': 'tpaa.p1.sensor.azimuth_error_p95',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.azimuth_error_p95',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-019',
        'name': 'ELEVATION_ERROR_BIAS',
        'semantic_id': 'tpaa.p1.sensor.elevation_error_bias',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.elevation_error_bias',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-020',
        'name': 'ELEVATION_ERROR_P95',
        'semantic_id': 'tpaa.p1.sensor.elevation_error_p95',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'rad',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.elevation_error_p95',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-SNS-021',
        'name': 'RADIAL_POSITION_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.sensor.radial_position_error_rmse',
        'semantic_version': 1,
        'family': 'SENSOR_ACCURACY',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.sensor.radial_position_error_rmse',
        'algorithm_version': '1.0.2',
        'delivery_milestone': 'M2',
        'delivery_batch': 'P1_FOUNDATION_32',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-001',
        'name': 'TRACK_INITIATION_TIME',
        'semantic_id': 'tpaa.p1.track.initiation_time',
        'semantic_version': 1,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.initiation_time',
        'algorithm_version': '1.0.5',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-002',
        'name': 'TRACK_POSITION_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.track.position_error_rmse',
        'semantic_version': 1,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.position_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-003',
        'name': 'TRACK_VELOCITY_ERROR_RMSE',
        'semantic_id': 'tpaa.p1.track.velocity_error_rmse',
        'semantic_version': 1,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'm/s',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.velocity_error_rmse',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-004',
        'name': 'TRACK_CONTINUITY',
        'semantic_id': 'tpaa.p1.track.continuity',
        'semantic_version': 1,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'ratio',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.continuity',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-005',
        'name': 'TRACK_DROP_COUNT',
        'semantic_id': 'tpaa.p1.track.drop_count',
        'semantic_version': 1,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 'count',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.drop_count',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-006',
        'name': 'TRACK_REACQUISITION_TIME',
        'semantic_id': 'tpaa.p1.track.reacquisition_time',
        'semantic_version': 2,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.reacquisition_time',
        'algorithm_version': '1.0.4',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
    MappingProxyType({
        'metric_code': 'P1-TRK-007',
        'name': 'TRACK_AGE',
        'semantic_id': 'tpaa.p1.track.age',
        'semantic_version': 2,
        'family': 'TRACK_PERFORMANCE',
        'subject_type': 'MISSION_SYSTEM_INSTANCE',
        'unit': 's',
        'value_kind': 'NUMERIC',
        'algorithm_id': 'alg.tpaa.p1.track.age',
        'algorithm_version': '1.0.3',
        'delivery_milestone': 'M3',
        'delivery_batch': 'P1_REMAINDER_84',
        'observation_lane': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'publication_route': 'SYSTEM_PERFORMANCE_OBSERVATION',
        'structured_output_schema_id': None,
        'p1_longitudinal_trend_eligibility': True,
    }),
)
